fix LinuxAlsaSpeakerVolumeControlCapability
Fix for TypeError: amixer.stdout.matchAll is not a function error
1) amixer.stdout has buffer type and must be converted toString
https://stackoverflow.com/a/34909314
2) String.prototype.matchAll replaced with local function from
https://stackoverflow.com/a/63005798, because
after converting stdout to string matchAll throw a 
TypeError: String.prototype.matchAll called with a non-global RegExp argument
https://stackoverflow.com/a/60290199